FROM python:3.11.4-slim

# Set the working directory to /app
WORKDIR /app

# Copy server files to /app
COPY server/requirements.txt /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the server files to /app
COPY server /app

# Expose the ports your servers are using
EXPOSE 65488 8001

# Run app.py when the container launches
CMD ["python", "app.py"]
